# Generated by Django 2.1.5 on 2019-02-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('volkswagen', 'Volkswagen'), ('mitsubishi', 'Mitsubishi'), ('ford', 'Ford '), ('lamborghini', 'Lamborghini')], max_length=256)),
                ('model', models.CharField(choices=[('model1', 'Model1'), ('model2', 'Model2'), ('model3', 'Model3'), ('model4', 'Model4')], max_length=256)),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('nameOfOvner', models.CharField(max_length=256)),
            ],
        ),
    ]
