# Generated by Django 2.1.5 on 2019-02-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
