# Generated by Django 2.1.5 on 2019-02-08 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'buyer', 'verbose_name_plural': 'List of buyers'},
        ),
    ]
